@startuml
actor User
User -> Auber: attempts arrest

alt Auber is near Enemy

    Auber -> Enemy: arrests
    Enemy -> Auber: follows
    User -> Auber: moves to teleporter
    User -> Auber: teleports to jail
    Enemy -> Jail: teleports to
 
end
@enduml