@startuml
start

repeat:Idle;
    -> Auber makes contact with teleport pad;
    :ReadyToTeleport;
    -> User clicks the teleport menu;
    :SelectingRoom;
    if (Auber has arrested enemies\nAnd Player selects jail) then (Yes)
        :Jail enemies;
    else (No)
        :Teleport;
        ->Auber Teleports to room;
        :InRoom;
    endif
@enduml
