@startuml
state "TryUseAbility" as TryUseAbility
state "Using Ability" as UsingAbility
state "Ability Disabled" as AbilityDisabled

[*] --> Idle
Idle -> TryUseAbility: Auber makes contact with an enemy, or update() called
TryUseAbility --> UsingAbility: Entity uses ability
UsingAbility --> AbilityDisabled: Enemy is arrested
UsingAbility --> Cooldown: 5 seconds (Or equivalent use time) pass
Cooldown --> AbilityDisabled: Enemy is arrested
Cooldown --> Idle: 30 seconds(Or equivalent cooldown time) pass
AbilityDisabled --> [*]
Idle --> AbilityDisabled: Enemy is arrested
@enduml