@startuml
node Startup {
    [Launcher]
    [Main Menu]
}
node GameTypes{
    [Base Game]
    [Demo Mode]
    [Load Game]
    [Loads Data]
    [New Game]
}
database Assets {
    [Map]
    [Textures]
}
node Entities {
    [Entity]
    [Player]
    [Enemy]
    [NPC]
    node Controllers{
        [Enemy Manager]
        [NPC Manager]
    }
}
node Actors {
    [System Status Menu]
    [Teleport Menu]
    [Pause Menu]
    [Settings Menu]
}
node Sprites {
    [Teleporter]
    [System]
    [Healing Pod]
}
node MovementSystems{
    [Movement]
    [AiMovement]
    [UserMovement]
}
node Ability{
    () "IAbility"
    [Base Ability]
    [Attack Player]
    [Ghost Mode]
    [Global Slow down]
    [Faster System Damage]
    [Inactive]
    [Show Infiltrator]
    [Slow Down Target]
    [Speed up]
    [Freeze Target]
}
[Launcher] --> [Main Menu]: Launches
[Main Menu] --> GameTypes: Selects Game Type
[Demo Mode] --> [Base Game]
[Demo Mode] --> [Player]: Changes MovementSystem to AI
[Load Game] --> [Loads Data]:Loads game from file
[Loads Data]--> [Base Game]:Overwrites data
[New Game] --> [Base Game]: Starts a new instance
[Base Game] --> Assets: Loads
[Base Game] --> [Game World]: Has
[Base Game] --> [Hud]: Shows
GameTypes --> Entities: Updates
[Enemy Manager] --> [Enemy]: Controls
[Enemy] --> [System]: Sabotages
[Player] --> [Enemy Manager]: Owns and updates
[Player] --> [Enemy]: Arrests
[Teleporter] --> [Player]: Teleports
[Healing Pod] --> [Player]: Heals
Characters --> [Game World]: Are in
[Renderer] --> [Game World]: Renders
[Game World] --> [Contact Listener]: Uses
[Key Controls] --> [Player]: Controls
[Pause Menu] --> [Settings Menu]: Opens
[Settings Menu] --> [Key Controls]: Changes
[Hud] --> Actors: Shows
[System] --> [System Status Menu]: Informs
[NPC Manager] --> [NPC]: Controls
[Character Renderer] --> Characters: Renders
[Teleport Menu] --> [Teleport Process]: Informs
[Teleport Process] --> [Teleporter]: Controls function
[Teleporter] --> [Enemy]: Teleports to jail


[Entity]-->[Player]
[Entity]-->[Enemy]
[Entity]-->[NPC]
Entities-->Ability: Has
[Movement]-->[AiMovement]
[Movement]-->[UserMovement]
Entities-->MovementSystems: Moves Entity

IAbility --> [Base Ability]
[Base Ability] --> [Attack Player]
[Base Ability] --> [Ghost Mode]
[Base Ability] --> [Global Slow down]
[Base Ability] --> [Faster System Damage]
[Base Ability] --> [Inactive]
[Base Ability] --> [Show Infiltrator]
[Base Ability] --> [Slow Down Target]
[Base Ability] --> [Speed up]
[Base Ability] --> [Freeze Target]
@enduml