@startuml
actor User
alt Enemy is near a system
    loop until system is fully sabotaged
        Enemy -> System: sabotage
    end
    System -> User: sabotage notification
else Enemy is near User and Ability is triggered on contact
    Enemy -> User: Uses ability
else Try trigger ability, using random probability
    Enemy -> User: Uses ability
end
@enduml